app/Http/routes.php
<?php
use Illuminate\Http\Request;
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['middleware' => 'web'], function () {
	Route::auth();
	Route::get('/', 'CatalogsController@index');
	Route::get('/catalogs', 'CatalogsController@index');
	Route::get( '/home', 'HomeController@index');
	Route::resource('categories', 'CategoriesController');
	Route::resource('products', 'ProductsController');
	Route::post('cart', 'CartController@addProduct');
	Route::get('cart', 'CartController@show');
	Route::delete('cart/{product_id}', 'CartController@removeProduct');
	Route::put('cart/{product_id}', 'CartController@changeQuantity');
	Route::get('/getcookie', function(Request $request){
		return $request->cookie('cart');
	});
	Route::get('checkout/login', 'CheckoutController@login');
	Route::post('checkout/login', 'CheckoutController@postLogin');
	Route::get('checkout/address', 'CheckoutController@address');
	Route::post('checkout/address', 'CheckoutController@postAddress');
	Route::get('checkout/payment','CheckoutController@payment');
	Route::post('checkout/payment', 'CheckoutController@postPayment');
	Route::get('checkout/success', 'CheckoutController@success');
	Route::resource('orders', 'OrdersController', ['only'=>['index', 'edit', 'update'
	]]);
	Route::get('order-history', 'OrdersController@orderHistory');
	Route::get('order-history-detail/{id}', 'OrdersController@orderHistoryDetail');
	Route::get('notworking', function(){
		Alert::warning('This feature have not working yet', 'Sorry..')->autoclose(5000)->persistent("Close this");
		return redirect('/login');
	});

});

Route::group(['middleware' => 'api'], function(){
	Route::get('address/regencies', 'AddressController@regencies');
});

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $fillable = ['id', 'user_id', 'address_id', 'bank', 'sender', 'status', 'total_payment'];

    public function user(){
    	return $this->belongsTo('App\User');
    }

    public function details(){
    	return $this->hasMany('App\OrderDetail');
    }

    public function address(){
    	return $this->belongsTo('App\Address');
    }

    public function refreshTotalPayment(){
        $total_payment = 0;
        foreach ($this->details as $detail) {
            $total_payment += $detail->total_price;
        }
        $this->total_payment = $total_payment;
        $this->save();
    }

    public function getPaddedIdAttribute(){ 
        return str_pad($this->id, 6, 0,STR_PAD_LEFT);
    }

    public static function statusList(){
        return [
            'waiting-payment' => 'Menunggu Pembayaran',
            'packaging' => 'Order Sedang Dipersiapkan',
            'sent' => 'Paket Dikirim',
            'finished' => 'Paket Diterima'
        ];
    }

    public function getHumanStatusAttribute(){
        return static::statusList()[$this->status];
    }

    public static function allowedStatus(){
        return array_keys(static::statusList());
    }
}
 

app/Http/Controllers/CheckoutController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Requests\CheckoutLoginRequest;
use App\Http\Requests\CheckoutAddressRequest;
use Illuminate\Support\MessageBag;
use App\Support\CartService;
use App\Address;
use App\Product;
use App\User;
use App\Order;
use App\OrderDetail;
use Auth;

class CheckoutController extends Controller
{

    protected $cart;

    public function __construct(CartService $cart){
        $this->cart = $cart;

        $this->middleware('checkout.have-cart',[
            'only' => ['login', 'postlogin', 'address', 'postAddress', 'payment', 'postPayment']
        ]);

        $this->middleware('checkout.login-step-done',[
            'only' => ['address', 'postAddress', 'payment', 'postPayment']
        ]);

        $this->middleware('checkout.address-step-done', [
            'only' => ['payment', 'postPayment']
        ]);

        $this->middleware('checkout.payment-step-done', [
            'only' => ['success']
        ]);
    }

    //1. TAHAP LOGIN 

    public function login(){
        if(Auth::check()){
            return redirect('checkout/address');
        }
        else{
    	   return view('checkout.login');
        }
    }

    public function postLogin(CheckoutLoginRequest $request){
    	$email = $request->get('email');
    	$is_guest = $request->get('is_guest') > 0;
    	$password = $request->get('checkout_password');

    	if($is_guest){
    		return $this->guestCheckout($email);
    	}

    	return $this->authenticateCheckout($email, $password);
    }

    protected function authenticateCheckout($email, $password){
    	//login
        if(!Auth::attempt(['email' => $email, 'password' => $password])){
            //Authentication is Failed
            $errors = new MessageBag();
            $errors->add('email', 'Data user yang dimasukkan salah');
            return redirect('checkout/login')->withInput(compact('email','password')+['is_guest' => 0])->withErrors($errors);
        }

        $deleteCartCookie = $this->cart->merge();
        return redirect('checkout/address')->withCookie($deleteCartCookie);
    }

    protected function guestCheckout($email){
    	if($user = User::where('email', $email)->first()){
    		if($user->hasPassword()){
    			//(A) Logic ketika email ada di DB dengan password
    			$errors = new MessageBag();
    			$errors->add('checkout_password', 'Alamat email "'. $email .'" sudah terdaftar, silahkan masukan password.');
    			//redirect and change is_guest value
    			return redirect('checkout/login')->withErrors($errors)->withInput(compact('email') + ['is_guest' => 0]);
    		}
    		//(B) Logic ketika email di DB tanpa password
    		//show view to request new password
    		session()->flash('email', $email);
    		return view('checkout.ask-password');
    	}
    	//(C) Logic ketika email tidak ada di DB
        //save user data to session
        session(['checkout.email' => $email]);
        return redirect('checkout/address');
    }

    //2. TAHAP ADDRESS

    public function address(){
        return view('checkout.address');
    }

    //method ketika ada request Address
    public function postAddress(CheckoutAddressRequest $request){
        if(Auth::check()) return $this->authenticateAddress($request);
        return $this->guestAddress($request);   
    }

    //method authenticate address ketika sudah login
    protected function authenticateAddress(CheckoutAddressRequest $request){
        $address_id = $request->get('address_id');
        //clear_old
        session()->forget('checkout.address');
        if($address_id == 'new-address'){
            $this->saveAddressSession($request);
        }
        else{
            session(['checkout.address.address_id' => $address_id]);
        }
        return redirect('checkout/payment');
    }

    //method address ketika belum login
    protected function guestAddress(CheckoutAddressRequest $request){
        $this->saveAddressSession($request);
        return redirect('checkout/payment');
    }

    // method untuk menyimpan data session alamat
    protected function saveAddressSession(CheckoutAddressRequest $request){
        session([
            'checkout.address.name' => $request->get('name'),
            'checkout.address.detail' => $request->get('detail'),
            'checkout.address.province_id' => $request->get('province_id'),
            'checkout.address.regency_id' => $request->get('regency_id'),
            'checkout.address.phone' => $request->get('phone')
        ]);
    }

    //3. TAHAP PAYMENT
    public function payment(){
        return view('checkout.payment');
    }

    public function postPayment(Request $request){
        $this->validate($request, [
            'bank_name' => 'required|in:' . implode(',',array_keys(config('bank'))),
            'sender' => 'required'
        ]);

        session([
            'checkout.payment.bank' => $request->get('bank_name'),
            'checkout.payment.sender' => $request->get('sender')
        ]);

        if(Auth::check()) return $this->authenticatePayment($request);
        return $this->guestPayment($request);
    }

    //method authenticate address ketika sudah login
    protected function authenticatePayment(Request $request){
        $user = Auth::user();
        $bank = session('checkout.payment.bank');
        $sender = session('checkout.payment.sender');

        //create address
        $address = $this->setupAddress($user, session('checkout.address'));

        //create record order
        $order = $this->setupOrder($user->id, $bank, $sender, $address, $this->cart->details());

        //delete session data
        session()->forget('checkout');
        $this->cart->clearCartRecord();
        return redirect('checkout/success')->with(compact('order'));
    }

    //method payment ketika sudah login
    protected function guestPayment(Request $request){
        //create user account
        $user = $this->setupCustomer(session('checkout.email'), session('checkout.address.name'));

        //create address
        $bank = session('checkout.payment.bank');
        $sender = session('checkout.payment.sender');
        $address = $this->setupAddress($user, session('checkout.address'));

        //create record order
        $order = $this->setupOrder($user->id, $bank, $sender, $address, $this->cart->details());

        //delete session data 
        session()->forget('checkout');
        $deleteCartCookie = $this->cart->clearCartCookie();
        return redirect('checkout/success')->with(compact('order'))->withCookie($deleteCartCookie);
    }

    protected function setupCustomer($email, $name){
        $user = User::create(compact('email', 'name'));
        $user->role = 'customer';
        $user->save();
        return $user;
    }

    protected function setupAddress(User $customer, $addressSession){
        if(Auth::check() && isset($addressSession['address_id'])){
            return Address::find($addressSession['address_id']);
        }
        return Address::create([
            'user_id' => $customer->id,
            'name' => $addressSession['name'],
            'detail' => $addressSession['detail'],
            'regency_id' => $addressSession['regency_id'],
            'phone' => $addressSession['phone']
        ]);
    }

    protected function setupOrder($user_id, $bank, $sender, Address $address, $carts){
        $status = 'waiting-payment';
        $address_id = $address->id;
        $order = Order::create(compact('user_id', 'address_id', 'bank', 'sender', 'status'));
        foreach($carts as $product){
            OrderDetail::create([
                'order_id' => $order->id,
                'address_id' => $address->id,
                'product_id' => $product['id'],
                'quantity' => $product['quantity'],
                'price' => $product['detail']['price'],
                'fee' => Product::find($product['id'])->getCostTo($address->regency_id)
            ]);
        }

        return Order::find($order->id);
    }

    public function success(){
        return view('checkout.success');
    }

}

resources/views/checkout/address-choose.blade.php
{!! Form::open(['url' => '/checkout/address', 'method'=>'post', 'class' => 'form-horizontal']) !!}

    <div class="form-group {!! $errors->has('address_id') ? 'has-error' : '' !!}">
      {!! Form::label('address_id', 'Pilih Alamat', ['class' => 'col-md-4 control-label']) !!}
      <div class="col-md-6">
        @foreach (auth()->user()->addresses as $address)
        <div class="row">
          <div class="col-md-1">
            <label>
              {!! Form::radio('address_id', $address->id, null) !!}
            </label>
          </div>
          <div class="col-md-11">
            <address>
             <strong>{{ $address->name }}</strong> <br>
             {{ $address->detail }} <br>
             {{ $address->regency->name }}, {{ $address->regency->province->name }} <br>
             <abbr title="Phone">P:</abbr>  +62 {{ $address->phone }}
            </address>
          </div>
        </div>
        @endforeach
        <div class="row">
          <div class="col-md-1">
            <label>
              {!! Form::radio('address_id', 'new-address', null) !!}
            </label>
          </div>
          <div class="col-md-11">
            <strong>Alamat Baru</strong>
          </div>
        </div>
        <div class="row">
          {!! $errors->first('address_id', '<p class="help-block">:message</p>') !!}
        </div>
      </div>

    </div>

    <div id="js-new-address">
      @include('checkout.address-new-form')
    </div>

    <div class="form-group">
        <div class="col-md-6 col-md-offset-4">
            {!! Form::button('Lanjut <i class="fa fa-arrow-right"></i>', array('type' => 'submit', 'class' => 'btn btn-primary')) !!}
        </div>
    </div>

{!! Form::close() !!}

resources/views/checkout/address-form.blade.php
{!! Form::open(['url' => '/checkout/address', 'method'=>'post', 'class' => 'form-horizontal']) !!}

    @include('checkout.address-new-form')

    <div class="form-group">
        <div class="col-md-6 col-md-offset-4">
            {!! Form::button('Lanjut <i class="fa fa-arrow-right"></i>', array('type' => 'submit', 'class' => 'btn btn-primary')) !!}
        </div>
    </div> 

{!! Form::close() !!}

resources/views/checkout/address-new-form.blade.php
<div class="form-group {!! $errors->has('name') ? 'has-error' : '' !!}">
  {!! Form::label('name', 'Nama', ['class' => 'col-md-4 control-label']) !!}
  <div class="col-md-6">
    {!! Form::text('name', null, ['class'=>'form-control']) !!}
    {!! $errors->first('name', '<p class="help-block">:message</p>') !!}
  </div>
</div>

<div class="form-group {!! $errors->has('detail') ? 'has-error' : '' !!}">
  {!! Form::label('detail', 'Alamat', ['class' => 'col-md-4 control-label']) !!}
  <div class="col-md-6">
    {!! Form::textarea('detail', null, ['class'=>'form-control', 'rows' => 3]) !!}
    {!! $errors->first('detail', '<p class="help-block">:message</p>') !!}
  </div>
</div>

<div class="form-group {!! $errors->has('province_id') ? 'has-error' : '' !!}">
  {!! Form::label('province_id', 'Provinsi', ['class' => 'col-md-4 control-label']) !!}
  <div class="col-md-6">
    {!! Form::select('province_id', [''=>'']+DB::table('provinces')->lists('name','id'), null, ['class'=>'form-control', 'id' => 'province_selector']) !!}
    {!! $errors->first('province_id', '<p class="help-block">:message</p>') !!}
  </div>
</div>

<div class="form-group {!! $errors->has('regency_id') ? 'has-error' : '' !!}">
  {!! Form::label('regency_id', 'Kabupaten / Kota', ['class' => 'col-md-4 control-label']) !!}
  <div class="col-md-6">
    {!! Form::select('regency_id',
      old('province_id') !== null ? DB::table('regencies')->where('province_id', old('province_id'))->lists('name', 'id') : [],
      old('regency_id'), ['class'=>'form-control', 'id' => 'regency_selector']) !!}
    {!! $errors->first('regency_id', '<p class="help-block">:message</p>') !!}
  </div>
</div>

<div class="form-group {!! $errors->has('phone') ? 'has-error' : '' !!}">
  {!! Form::label('phone', 'Telepon', ['class' => 'col-md-4 control-label']) !!}
  <div class="col-md-6">
    <div class="input-group">
      <div class="input-group-addon">+62</div>
      {!! Form::text('phone', null, ['class'=>'form-control']) !!}
    </div>
    {!! $errors->first('phone', '<p class="help-block">:message</p>') !!}
  </div>
</div>

resources/views/checkout/address.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  @include('checkout.step')
  <div class="row">
    <div class="col-md-8">
      <div class="panel panel-default">
          <div class="panel-heading">Alamat Pengiriman</div>
          <div class="panel-body">
            @if (auth()->check())
              @include('checkout.address-choose')
            @else
              @include('checkout.address-form')
            @endif
          </div> 
      </div>
    </div>
    <div class="col-md-4">
      @include('checkout.cart-panel')
    </div>
  </div>
</div>
@endsection

resources/views/checkout/ask-password.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		@include('checkout.step')
		<div class="row">
			<div class="col-xs-12">
				<div class="panel panel-default">
					<div class="panel-heading">Permintaan Password</div>
					<div class="panel-body">
						@include('checkout.password-form')
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/checkout/cart-panel.blade.php
<div class="panel panel-default">
	<div class="panel-heading">Cart</div>
	<div class="panel-body">
		<table class="table table-condensed">
			<thead>
				<tr>
					<th style="width:50%">Produk</th>
					<th style="width:20%">Jumlah</th>
					<th style="width:30%">Harga</th>
				</tr>
			</thead>
			<tbody>
				@foreach($cart->details() as $order)
				<tr>
					<td data-th="Produk">{{ $order['detail']['name'] }}</td>

					<td data-th="Jumlah" class="text-center">{{ $order['quantity'] }}</td>

					<td data-th="Harga" class="text-right">Rp: {{ number_format($order['detail']['price']) }}</td>
				</tr>
				<tr>
					<td data-th="Subtotal">Total</td>
					<td data-th="Subtotal" class="text-right" colspan="2">Rp: {{ number_format($order['subtotal']) }}</td>
				</tr>
				@endforeach
			</tbody>
			<tfoot>
			@if(request()->is('checkout/payment'))
				<tr>
					<td data-th="Subtotal"><strong>Ongkos Kirim</strong></td>
					<td data-th="Subtotal" class="text-right" colspan="2"><strong>Rp. {{ number_format($cart->shippingFee()) }}</strong>
				</tr>
				<tr>
					<td><strong>SubTotal</strong></td>
					<td class="text-right" colspan="2"><strong>Rp. {{ number_format($cart->totalPrice() + $cart->shippingFee()) }}</strong></td>
				</tr>
			@else
				<td><strong>SubTotal</strong></td>
				<td class="text-right" colspan="2"><strong>Rp. {{ number_format($cart->totalPrice()) }}</strong></td>	
			@endif	
			</tfoot>
		</table>
	</div>
</div>

resources/views/checkout/login-form.blade.php
{!! Form::open(['url' => '/checkout/login', 'method' => 'post', 'class' => 'form-horizontal']) !!}
{{ csrf_field() }}

	<div class="form-group {!! $errors->has('email') ? 'has-error' : '' !!}">
		{!! Form::label('email', 'Email', ['class' => 'col-md-4 control-label']) !!}

		<div class="col-md-6">
			{!! Form::email('email', null, ['class' => 'form-control']) !!}
			{!! $errors->first('email', '<p class="help-block">:message</p>') !!}
		</div>
	</div>

	<div class="form-group {!! $errors->has('is_guest') ? 'has-error' : '' !!}">
		<div class="col-md-6 col-md-offset-4 radio">
			<p><label>{{ Form::radio('is_guest', 1, true) }} Saya adalah pelanggan baru</label></p>
			<p><label>{{ Form::radio('is_guest', 0) }} Saya adalah pelanggan tetap</label></p>
			{!! $errors->first('is_guest','<p class="help-block">:message</p>') !!}
		</div>
	</div>

	<div class="form-group {!! $errors->has('checkout_password') ? 'has-error' : '' !!}">
		{!! Form::label('checkout_password', 'Password', ['class' => 'col-md-4 control-label']) !!}

		<div class="col-md-6">
			{!! Form::password('checkout_password', ['class' => 'form-control']) !!}
			{!! $errors->first('checkout_password', '<p class="help-block">:message</p>') !!}

			<a href="{{ url('password/reset') }}">Lupa kata sandi</a>
		</div>
	</div>

	<div class="form-group">
		<div class="col-md-6 col-md-offset-4">
			{!! Form::button('Lanjut <i class="fa fa-arrow-right"></i>', array('type' => 'submit', 'class' => 'btn btn-primary')) !!}
		</div>
	</div>

{!! Form::close() !!}

resources/views/checkout/login.blade.php
@extends('layouts/app')

@section('content')
	<div class="container">
		@include('checkout.step')
		<div class="row">
			<div class="col-md-8">
				<div class="panel panel-default">
					<div class="panel-heading">Login atau Checkout tanpa mendaftar</div>
					<div class="panel-body">
					@if(session('status'))
						<div class="alert alert-success">
							{{ session('status') }}
						</div>
					@endif	
						@include('checkout.login-form')
					</div>
				</div>
			</div>
			<div class="col-md-4">
				@include('checkout.cart-panel') 
			</div>
		</div>
	</div>	
@endsection

resources/views/checkout/password-form.blade.php
{!! Form::open(['url' => '/password/email', 'method' => 'post', 'class' => 'form-horizontal']) !!}

	<div class="form-group {!! $errors->has('email') ? 'has-error' : '' !!}">
		{!! Form::label('email', 'Email Address', ['class' => 'col-md-4 control-label']) !!}

		<div class="col-md-6">
			{!! Form::email('email', session()->has('email') ? session('email') : null, ['class' => 'form-control']) !!}

			<p class="help-block">Nampaknya kamu pernah berbelanja di Tokoku. Klik "Kirim petunjuk" untuk meminta password baru.</p>
			{!! $errors->first('email', '<p class="help-block">:message</p>') !!}
		</div>
	</div>

	<div class="form-group">
		<div class="col-md-6 col-md-offset-4">
			{!! Form::button('Kirim petunjuk <i class="fa fa-arrow-right"></i>', array('type' => 'submit', 'class' => 'btn btn-primary')) !!}
		</div>
	</div>
{!! Form::close() !!}

resources/views/checkout/payment-form.blade.php
{!! Form::open(['url' => '/checkout/payment', 'method'=>'post', 'class' => 'form-horizontal']) !!}

<div class="form-group {!! $errors->has('bank_name') ? 'has-error' : '' !!}">
	{!! Form::label('bank_name', 'Pilih Bank yang Anda gunakan', ['class' => 'col-md-4 control-label']) !!}

	<div class="col-md-6">
	{!! Form::select('bank_name', bankList(), null, ['class'=>'form-control js-selectize']) !!}
	{!! $errors->first('bank_name', '<p class="help-block">:message</p>') !!}
	</div>
</div>

<div class="form-group {!! $errors->has('sender') ? 'has-error' : '' !!}">
	{!! Form::label('sender', 'Nama Pengirim', ['class' => 'col-md-4 control-label']) !!}

	<div class="col-md-6">
	{!! Form::text('sender', null, ['class'=>'form-control']) !!}
	{!! $errors->first('sender', '<p class="help-block">:message</p>') !!}
	</div>
</div>

<div class="form-group">
	<div class="col-md-6 col-md-offset-4">
		{!! Form::button('<i class="fa fa-lock"></i> Konfirmasi Pesanan', array('type' => 'submit', 'class' => 'btn btn-primary')) !!}
	</div>
</div>

{!! Form::close() !!}

resources/views/checkout/payment.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	@include('checkout.step')
	<div class="row">
		<div class="col-md-8">
			<div class="panel panel-default">
				<div class="panel-heading">Pembayaran</div>
				<div class="panel-body">
					@include('checkout.payment-form')
				</div>
			</div>
		</div>
		<div class="col-md-4">
			@include('checkout.cart-panel')
		</div>
	</div>
</div>
@endsection

resources/views/checkout/step.blade.php
<div class="row">
	<div class="col-xs-12">
		<ul class="nav nav-pills nav-justified thumbnail setup-panel">
			<li class="{{ Request::is('checkout/login') ? 'active' : 'disabled' }}">
				<a><h4 class="list-group-item-heading">Login</h4>
				</a>
			</li>
			<li class="{{ Request::is('checkout/address') ? 'active' : 'disabled' }}">
				<a><h4 class="list-group-item-heading">Alamat</h4>
				</a>
			</li>
			<li class="{{ Request::is('checkout/payment') ? 'active' : 'disabled' }}">
				<a><h4 class="list-group-item-heading">Payment</h4>
				</a>
			</li>
		</ul>
	</div>
</div>

resources/views/checkout/success.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title"><strong>Berhasil </strong>melalukan pemesanan!</h3>
					</div>
					<div class="panel-body">
						<p>Hi <strong>{{ session('order')->user->name }}</strong></p>
						<p></p>
						<p>Terima kasih telah berbelanja di Tokoku.<br>
						Untuk melakukan pembayaran dengan {{ config('bank')[session('order')->bank]['title'] }} </p>
						<ol>
							<li>
								Silahkan transfer ke rekening <strong>{{ config('bank')[session('order')->bank]['bank'] }} {{ config('bank')[session('order')->bank]['number'] }} An. {{ config('bank')[session('order')->bank]['name'] }} </strong>
							</li>
							<li>
								Ketika melakukan pembayaran sertakan nomor pemesanan <strong>{{ session('order')->padded_id }}</strong>
							</li>
							<li>
								Total pembayaran : <strong>Rp. {{ number_format(session('order')->total_payment) }}</strong> 
							</li>
						</ol>
					</div>
					<div class="panel-footer">
						<a href="/">Lanjutkan Belanja</a>
					</div>
				</div>		
			</div>
		</div>
	</div>
@endsection