app/Http/routes.php
<?php
use Illuminate\Http\Request;
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['middleware' => 'web'], function () {
	Route::auth();
	Route::get('/', 'CatalogsController@index');
	Route::get('/catalogs', 'CatalogsController@index');
	Route::get( '/home', 'HomeController@index');
	Route::resource('categories', 'CategoriesController');
	Route::resource('products', 'ProductsController');
	Route::post('cart', 'CartController@addProduct');
	Route::get('cart', 'CartController@show');
	Route::delete('cart/{product_id}', 'CartController@removeProduct');
	Route::put('cart/{product_id}', 'CartController@changeQuantity');
	Route::get('/getcookie', function(Request $request){
		return $request->cookie('cart');
	});
	Route::get('checkout/login', 'CheckoutController@login');
	Route::post('checkout/login', 'CheckoutController@postLogin');
	Route::get('checkout/address', 'CheckoutController@address');
	Route::post('checkout/address', 'CheckoutController@postAddress');
	Route::get('checkout/payment','CheckoutController@payment');
	Route::post('checkout/payment', 'CheckoutController@postPayment');
	Route::get('checkout/success', 'CheckoutController@success');
	Route::resource('orders', 'OrdersController', ['only'=>['index', 'edit', 'update'
	]]);
	Route::get('order-history', 'OrdersController@orderHistory');
	Route::get('order-history-detail/{id}', 'OrdersController@orderHistoryDetail');
	Route::get('notworking', function(){
		Alert::warning('This feature have not working yet', 'Sorry..')->autoclose(5000)->persistent("Close this");
		return redirect('/login');
	});

});

Route::group(['middleware' => 'api'], function(){
	Route::get('address/regencies', 'AddressController@regencies');
});

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $fillable = ['id', 'user_id', 'address_id', 'bank', 'sender', 'status', 'total_payment'];

    public function user(){
    	return $this->belongsTo('App\User');
    }

    public function details(){
    	return $this->hasMany('App\OrderDetail');
    }

    public function address(){
    	return $this->belongsTo('App\Address');
    }

    public function refreshTotalPayment(){
        $total_payment = 0;
        foreach ($this->details as $detail) {
            $total_payment += $detail->total_price;
        }
        $this->total_payment = $total_payment;
        $this->save();
    }

    public function getPaddedIdAttribute(){ 
        return str_pad($this->id, 6, 0,STR_PAD_LEFT);
    }

    public static function statusList(){
        return [
            'waiting-payment' => 'Menunggu Pembayaran',
            'packaging' => 'Order Sedang Dipersiapkan',
            'sent' => 'Paket Dikirim',
            'finished' => 'Paket Diterima'
        ];
    }

    public function getHumanStatusAttribute(){
        return static::statusList()[$this->status];
    }

    public static function allowedStatus(){
        return array_keys(static::statusList());
    }
}
 

app/Http/Controllers/OrdersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Order;
use App\OrderDetail;
use Session;
use Auth;

class OrdersController extends Controller
{
	public function __construct(){
		$this->middleware('auth');
	}

	public function index(Request $request){
		$status = $request->get('status');
		$orders = Order::where('status', 'LIKE', '%'.$status.'%');
		if ($request->has('q')) {
			$q = $request->get('q');
			$orders = $orders->where(function($query) use ($q) {
				$query->where('id', $q)
					->orWhereHas('user', function($user) use ($q) {
						$user->where('name', 'LIKE', '%'.$q.'%');
					});
			});
		}
		$orders = $orders->paginate(10);
		return view('orders.index', compact('orders', 'status','q'));
	}

	public function edit($id){
		$order = Order::find($id);
		return view('orders.edit')->with(compact('order'));
	}

	public function update(Request $request, $id){
		$order = Order::find($id);

		$this->validate($request, [
		'status' => 'required|in:' . implode(',',Order::allowedStatus())
		]);

		$order->update($request->only('status'));
		
		Session::flash('flash_notification', ["level"=>"success", "message"=>"Order ".$order->padded_id." berhasil disimpan"]);
		return redirect()->route('orders.index');
	} 

	public function orderHistory(){
		$orders = Order::where('user_id', Auth::user()->id)->get();
		return view('orders.order-history', compact('orders'));
	}

	public function orderHistoryDetail(Request $request, $id){
		$details = OrderDetail::where('order_id', $id)->get();
		$order = Order::where('id',$id)->first(); 
		return view('orders.order-history-detail', compact('details','order'));
	}
}
 

resources/views/orders/detail.blade.php
<table class="table table-condensed">
  <thead>
    <tr>
      <th style="width:50%">Produk</th>
      <th style="width:20%">Jumlah</th>
      <th style="width:30%">Harga</th>
    </tr>
  </thead>
  <tbody>
    @foreach($order->details as $detail)
    <tr>
      <td data-th="Produk">{{ $detail->product->name }}</td>
      <td data-th="Jumlah" class="text-center">{{ $detail->quantity }}</td>
      <td data-th="Harga" class="text-right">{{ number_format($detail->price) }}</td>
    </tr>
    <tr>
      <td data-th="Subtotal">Subtotal</td>
      <td data-th="Subtotal" class="text-right" colspan="2">Rp{{ number_format($detail->total_price) }}</td>
    </tr>

    @endforeach
  </tbody>
  <tfoot>
    <tr>
      <td data-th="Subtotal"><strong>Ongkos Kirim</strong></td>
      <td data-th="Subtotal" class="text-right" colspan="2"><strong>Rp{{ number_format($order->total_fee) }}</strong></td>
    </tr>
    <tr>
      <td><strong>Total</strong></td>
        <td class="text-right" colspan="2"><strong>Rp{{ number_format($order->total_payment) }}</strong></td>
    </tr>
  </tfoot>
</table>

resources/views/orders/edit.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="panel panel-default">
          <div class="panel-heading"><h3>Edit {{ $order->title }}</h3></div>
          <div class="panel-body">
            {!! Form::model($order, ['route' => ['orders.update', $order], 'method'=>'patch', 'class'=>'form-horizontal'])!!}
            <div class="col-md-3"></div>
            <div class="col-md-7">
              @include('orders.form', ['model' => $order])
            </div>
            <div class="col-md-2"></div>
            {!! Form::close() !!} 
          </div>
        </div>
      </div>
    </div>
  </div> 
@endsection

resources/views/orders/form.blade.php
<div class="form-group">
  <div class="row">
    <div class="col-md-4">
      <label>Order #</label>
    </div>
    <div class="col-md-6">
      {{ $order->padded_id }}
    </div>
  </div>
</div>

<div class="form-group">
  <div class="row">
    <div class="col-md-4">
      <label>Customer</label>
    </div>
    <div class="col-md-6">
      {{ $order->user->name }}
    </div>
  </div>
</div>

<div class="form-group">
  <div class="row">
    <div class="col-md-4">
      <label>Alamat Pengiriman</label>
    </div>
    <div class="col-md-6">
      <address>
       <strong>{{ $order->address->name }}</strong> <br>
       {{ $order->address->detail }} <br>
       {{ $order->address->regency->name }}, {{ $order->address->regency->province->name }} <br>
       <abbr title="Phone">P:</abbr>  +62 {{ $order->address->phone }}
      </address>
    </div>
  </div>
</div>

<div class="form-group">
  <div class="row">
    <div class="col-md-4">
      <label>Detail</label>
    </div>
    <div class="col-md-6">
      @include('orders.detail', compact('order'))
    </div>
  </div>
</div>

<div class="form-group{{ $errors->has('status') ? ' has-error' : '' }}">
    <div class="row">
      <div class="col-md-4">
        <label class="control-label">Status</label>
      </div>
      <div class="col-md-6">
          {!! Form::select('status', App\Order::statusList(), null, ['class'=>'form-control']) !!}
          {!! $errors->first('status', '<p class="help-block">:message</p>') !!}
      </div>
    </div>
</div>

<div class="form-group text-center">
{!! Form::submit('Simpan', ['class'=>'btn btn-primary']) !!}
</div>

resources/views/orders/index.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        {!! Form::open(['url' => 'orders', 'method'=>'get', 'class'=>'form-inline']) !!}

            <div class="form-group {!! $errors->has('q') ? 'has-error' : '' !!}">
              {!! Form::text('q', isset($q) ? $q : null, ['class'=>'form-control',
                    'placeholder' => 'Order ID/Customer...']) !!}
              {!! $errors->first('q', '<p class="help-block">:message</p>') !!}
            </div>

            <div class="form-group {!! $errors->has('status') ? 'has-error' : '' !!}">
              {!! Form::select('status', [''=>'Semua status']+App\Order::statusList(),
                isset($status) ? $status : null, ['class'=>'form-control']) !!}
              {!! $errors->first('status', '<p class="help-block">:message</p>') !!}
            </div>

          {!! Form::submit('Cari', ['class'=>'btn btn-primary']) !!}
        {!! Form::close() !!}
        <div class="table-responsive"> 
          <table class="table">
          <thead>
            <tr>
              <td>Order #</td>
              <td>Customer</td>
              <td>Status</td>
              <td>Pembayaran</td>
              <td>Update terakhir</td>
            </tr>
          </thead>
          <tbody>
            @forelse($orders as $order)
            <tr>
              <td><a href="{{ route('orders.edit', $order->id)}}">{{ $order->padded_id }}</a></td>
              <td>{{ $order->user->name }}</td>
              <td>{{ $order->human_status }}</td>
              <td>
                Total: <strong>{{ number_format($order->total_payment) }} </strong><br>
                Transfer ke : {{ config('bank-accounts')[$order->bank]['bank'] }} <br>
                Dari : {{ $order->sender }}
              </td>
              <td>{{ $order->updated_at }}</td>
            </tr>
            @empty
              <tr>
                <td colspan="4">Tidak ada order yang ditemukan</td>
              </tr>
            @endforelse
          </tbody>
          </table>
        </div>
        {!! $orders->appends(compact('status', 'q'))->links() !!}
      </div>
    </div>
  </div>
@endsection

resources/views/orders/order-history-detail.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="panel panel-default">
          <div class="panel-heading"><h3>Order History <small>Padded ID : <strong>{{ $order->padded_id }}</strong></small></h3></div>
          <div class="panel-body">
              <table class="cart table table-hover table-condensed">
                <thead> 
                  <tr>
                    <th style="width:40%">Product</th>
                    <th style="width:10%" class="text-center">Quantity</th>
                    <th style="width:15%" class="text-center">Price</th>
                    <th style="width:15%" class="text-center">Fee</th>
                    <th style="width:15%" class="text-center">Total Price</th>
                  </tr>
                </thead>
                <tbody>
                @foreach($details as $detail)
                    <tr>
                      <td>
                        <div class="row">
                            <div class="col-md-2"> 
                              <img src="{{ $detail->product->photo_path }}" alt="..." width="40" height="40" class="img-responsive">
                            </div>
                            <div class="col-md-10">
                              {{ $detail->product->name }}
                            </div>
                        </div>
                        <br>
                      </td>
                      <td class="text-center">
                        {{ $detail->quantity }}
                      </td>
                      <td class="text-center">
                        {{ $detail->price }}
                      </td>
                      <td class="text-center">
                        {{ $detail->fee }}
                      </td>
                      <td class="text-center">
                        {{ $detail->total_price }}
                      </td>
                    </tr>
                @endforeach
                </tbody>
              </table>
          </div>
        </div>
        <a href="{{ url('order-history') }}" class="btn btn-primary"><i class="glyphicon glyphicon-chevron-left">Back</i></a>
      </div>
    </div>
  </div> 
@endsection

resources/views/orders/order-history.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="panel panel-default">
          <div class="panel-heading"><h3>Order History</h3></div>
          <div class="panel-body">
            <div class="table-responsive">
              <table class="table">
                <thead> 
                  <tr>
                    <th style="width:10%">Padded ID</th>
                    <th style="width:25%">Address</th>
                    <th style="width:8%">Bank</th>
                    <th style="width:8%">Sender</th>
                    <th style="width:12%">Total Payment</th>
                    <th style="width:10%">Status</th>
                    <th style="width:10%">Details</th>
                  </tr>
                </thead>
                <tbody>
                @forelse ($orders as $order)
                    <tr>
                      <td>{{ $order->padded_id }}</td>
                      <td>
                        <address>
                         <strong>{{ $order->address->name }}</strong> <br>
                         {{ $order->address->detail }} <br>
                         {{ $order->address->regency->name }}, {{ $order->address->regency->province->name }} <br>
                         <abbr title="Phone">P:</abbr>  +62 {{ $order->address->phone }}
                        </address>
                      </td>
                      <td>{{ config('bank')[$order->bank]['bank'] }}</td>
                      <td>{{ $order->sender }}</td>
                      <td>{{ $order->total_payment }}</td>
                      <td>
                        @if($order->status == "waiting-payment")
                          <span class="label label-default">{{ $order->human_status }}</span>
                        @elseif($order->status == "packaging")
                          <span class="label label-info">{{ $order->human_status }}</span>
                        @elseif($order->status == "sent")
                          <span class="label label-primary">{{ $order->human_status }}</span>
                         @elseif($order->status == "finished")
                          <span class="label label-success">{{ $order->human_status }}</span>
                        @endif 
                      </td>
                      <td>
                       <a href="{{ url('order-history-detail', $order->id) }}" class="btn btn-danger" aria-label="Left Align">
                        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                      </a>
                      </td>
                    </tr>
                @empty
                    <tr>
                      <td colspan ="7" class="text-center">
                          <h1>:(</h1>
                          <p>Order kamu masih kosong</p>
                          <p><a href="{{ url('/catalogs') }}">Yuk, belanja di Tokoku<i class="fa fa-arrow-right"></i></a></p>
                        </div>
                      </td>
                    </tr>
                @endforelse
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div> 
@endsection